In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
lst = [1,2,3,4]
print(arr)
print(lst)

[1 2 3 4]
[1, 2, 3, 4]


In [22]:
#n - dimentional array
arr2d = np.array([[1,2,3], [4,5,6]])
arr3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print("2D array = " , arr2d)
print("3D array = " , arr3d)

2D array =  [[1 2 3]
 [4 5 6]]
3D array =  [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
zeros = np.zeros((4, 3))     # 4x3 matrix of 0s
ones = np.ones((2, 4))       # 2x4 matrix of 1s
range_arr = np.arange(0, 10, 2)  # 0 to 10 with step 2 ||  10 excluded
linear = np.linspace(0, 1, 5)    # 5 numbers evenly spaced between 0 and 1
print(zeros)
print(ones)
print(range_arr)
print(linear)

[0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [32]:
# print(arr3d.max()) # maximum value of array
# print(arr3d.min()) # minimum value of array
# print(arr3d.mean()) # mean value of array
# print(arr3d.ndim)  # gives the dimentions of array
# print(arr2d.reshape(3,2)) # reshapes the array i.e. arr2d is 2x3 has 6 elements so it reshapes it into 3x2 which also has 6 elements number of element should be the same after reshape 
print(arr2d.ravel()) # convert backs to 1D but doesn't change the original array
print(arr2d.nonzero())


[1 2 3 4 5 6]
(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))


In [46]:
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])
print(arr[1,2])
print(arr[ :, 0:2])
print(arr[ :2, -1:-3:-1])

print(arr[arr>40])

60
[[10 20]
 [40 50]
 [70 80]]
[[30 20]
 [60 50]]
[50 60 70 80 90]


In [52]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)
print(a * b)   
print(a ** 2)  

print(a @ b) #dot multiplication
# print(np.cross(a,b)) # cross product but dimensions must be 2 or 3

[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]
300


In [ ]:
a = np.array([1, 2, 3])
b = 2
print(a + b)  # [3 4 5]

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)

[3 4 5]
[[11 22 33]
 [14 25 36]]


In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.sum())         # sum of all values
print(arr.mean())        # mean
print(arr.std())         #  standard deviation
print(arr.max(axis=0))   # [4 5 6]  – max of each column(axis=0)
print(arr.min(axis=1))   # [1 4]    – min of each row(axis=1)


45
5.0
2.581988897471611
[7 8 9]
[1 4 7]


In [5]:
arr = np.array([[1, 2, 10], [4, 5, 21], [7, 8, 9]])
print(np.linalg.diagonal(arr)) # give a diagonal array
print(np.linalg.det(arr))
print(np.linalg.eig(arr))
print(np.linalg.inv(arr))
print(np.linalg.matrix_transpose(arr))

[1 5 9]
68.99999999999996
EigResult(eigenvalues=array([23.19156524, -0.38091847, -7.81064677]), eigenvectors=array([[-0.32915417, -0.73125501, -0.43355666],
       [-0.74384947,  0.68119232, -0.73021158],
       [-0.58167474, -0.03525811,  0.52803378]]))
[[-1.7826087   0.89855072 -0.11594203]
 [ 1.60869565 -0.88405797  0.27536232]
 [-0.04347826  0.08695652 -0.04347826]]
[[ 1  4  7]
 [ 2  5  8]
 [10 21  9]]


In [103]:
np.random.seed(0)
print(np.random.randint(1, 10, (3, 3)))  # 3x3 random integers
print(np.random.normal(0, 1, 5)) 

[[6 1 4]
 [4 8 4]
 [6 3 5]]
[-0.29139398 -0.13309028 -0.1730696  -1.76165167 -0.08767307]


In [114]:
# arr = np.array([[1,2,3,4,5],
#                 [6,7,8,9,10],
#                 [11,12,13,14,15],
#                 [16,17,18,19,20],
#                 [21,22,23,24,25]])
arr = np.arange(1,26).reshape(5,5)
print(arr)
print(arr[:,1])
print(arr[2,:])
print(arr[:3,:3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 2  7 12 17 22]
[11 12 13 14 15]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [130]:
np.random.seed(0)
arr = np.random.rand(100)
print(arr)
mean = arr.mean()
print(f"Mean = {mean}")
std = arr.std()
print(f"Std = {std}")
above_mean = arr[arr>mean].size # alternate count = (arr > mean).sum()
print(above_mean)
print(arr[arr>mean])

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194
 0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
 0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263
 0.31542835 0.36371077 0.57019677 0.43860151 0.98837384 0.10204481
 0.20887676 0.16130952 0.65310833 0.2532916  0.46631077 0.24442559
 0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
 0.82099323 0.09710128 0.83794491 0.09609841 0.97645947 0.4686512
 0.97676109 0.60484552 0.73926358 0.03918779 0.28280696 0.12019656
 0.2961402  0.11872772 0.31798318 0.41426299 0.0641475  0.69247212
 0.56660145 0.26538949 0.52324805 0.09394051 0.5759465  0.9292962

In [ ]:
#Normalize rows of a matrix.
# Given a 2D array X of shape (n, m), 
# subtract the row mean and divide by the row std for each row (resulting row-wise mean 0 and std 1).

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
# for a in arr:
#     mean = a.mean()
#     std = a.std()
#     a = (a-mean)/std
#     print(a)

row_means = arr.mean(axis=1, keepdims=True)
print(row_means)
row_stds = arr.std(axis=1, keepdims=True)
print(row_stds)

Z = (arr - row_means)/row_stds
print(Z)


[-1.22474487  0.          1.22474487]
[-1.22474487  0.          1.22474487]
[-1.22474487  0.          1.22474487]
[[2.]
 [5.]
 [8.]]
[[0.81649658]
 [0.81649658]
 [0.81649658]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


In [ ]:

arr = np.array([[4,7,2,9],
                [7,5,8,1],
                [2,8,3,6],
                [9,1,6,0]])

eigen = np.linalg.eig(arr)
eigenvectors = eigen.eigenvectors
eigenValues = eigen.eigenvalues

dioganal_of_eigValues = np.diag(eigenValues) #diagonal matrix of eigen values
Transpose_of_eigVectors = eigenvectors.transpose()

original_matrix = eigenvectors @ dioganal_of_eigValues @ Transpose_of_eigVectors
print(original_matrix.round())

np.allclose(arr, original_matrix) 

[[4. 7. 2. 9.]
 [7. 5. 8. 1.]
 [2. 8. 3. 6.]
 [9. 1. 6. 0.]]


True

In [ ]:
arr = np.array([1,2,5,-999,8,5,3,-999,5,6,7])
cleanArr = arr[arr != -999]
mean = cleanArr.mean()
print(mean)
print(np.median(cleanArr))

4.666666666666667
5.0


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# dotProduct = A @ B.T # else np.dot(A, B)
# dot = np.dot(A,B.T)
# mtml = np.matmul(A, B.T)
# print(dotProduct)
# print(dot)
# print(mtml)

# C = A*B
# print(C)

row_sums = A.sum(axis=1, keepdims=True)
A_with_sum = np.hstack((A, row_sums))
print(A_with_sum)
print(np.concatenate((A,row_sums),axis=1))



[[ 1  2  3  6]
 [ 4  5  6 15]]
[[ 1  2  3  6]
 [ 4  5  6 15]]


In [ ]:
np.random.seed(0)
a = np.random.randint(1,100, (5,5))
print(a)
# print(np.hstack((a, a.var(axis=1,keepdims=True))))
b = np.random.randint(1,10, (5,5))
# print(b)
c , d, e = np.split(a, (3,4))
print(c)

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]]
[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]]


In [62]:
arr = np.array([[1,2,3],
                [4,5,6]])

arr2 = np.array([[7,8,9],
                 [11,12,13]])

np.where(arr>3, arr+1, arr)
np.put(arr,[1,3,5], -99 )